spring.config.import=optional:classpath:application-local.properties

# Oracle DataSource
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@${DB_HOST:localhost}:${DB_PORT:1521}/${DB_SERVICE:ORCLPDB1}
spring.datasource.username=${DB_USER:SUBSCRIBER_MANAGER}
spring.datasource.password=${DB_PASSWORD:}

# Server
server.port=${PORT:4000}
