# Oracle Schema additions for subscription lifecycle actions

-- =========================
-- SUBSCRIPTIONS: lifecycle-mutable fields
-- =========================

ALTER TABLE SUBSCRIPTION_MANAGER.SUBSCRIPTIONS
    ADD MSISDN VARCHAR2(400);

ALTER TABLE SUBSCRIPTION_MANAGER.SUBSCRIPTIONS
    ADD SIM_ICCID VARCHAR2(400);

-- =========================
-- OPERATIONS TABLE
-- =========================

-- Sequence for OPERATIONS table
CREATE SEQUENCE SUBSCRIPTION_MANAGER.SEQ_OPERATION_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- OPERATIONS table
CREATE TABLE SUBSCRIPTION_MANAGER.OPERATIONS (
    ID              NUMBER PRIMARY KEY,
    SUBSCRIPTION_ID NUMBER NOT NULL,
    OPERATION_TYPE  VARCHAR2(50) NOT NULL,
    STATUS          VARCHAR2(20) NOT NULL,
    CREATED_DATE    DATE NOT NULL,
    UPDATED_DATE    DATE,
    ERROR_MESSAGE   VARCHAR2(4000),
    DESCRIPTION     VARCHAR2(4000),
    OPERATION_DATA  VARCHAR2(4000),
    CONSTRAINT FK_OPERATIONS_SUBSCRIPTION
        FOREIGN KEY (SUBSCRIPTION_ID)
        REFERENCES SUBSCRIPTION_MANAGER.SUBSCRIPTIONS (ID)
);

-- Trigger for automatic OPERATION ID generation
CREATE OR REPLACE TRIGGER SUBSCRIPTION_MANAGER.TRG_OPERATION_ID
BEFORE INSERT ON SUBSCRIPTION_MANAGER.OPERATIONS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SUBSCRIPTION_MANAGER.SEQ_OPERATION_ID.NEXTVAL
        INTO :NEW.ID
        FROM DUAL;
    END IF;
END;
/
