# Oracle Schema additions for generic subscription resources
# (subscription-resources-module — IP, VLAN, CPE, PORT, EQUIPMENT, NODE;
#  MSISDN/SIM_ICCID remain dedicated columns on SUBSCRIPTIONS, not modeled here)

-- =========================
-- RESOURCES TABLE
-- =========================

-- Sequence for RESOURCES table
CREATE SEQUENCE SUBSCRIPTION_MANAGER.SEQ_RESOURCE_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- RESOURCES table
CREATE TABLE SUBSCRIPTION_MANAGER.RESOURCES (
    ID              NUMBER PRIMARY KEY,
    SUBSCRIPTION_ID NUMBER NOT NULL,
    RESOURCE_TYPE   VARCHAR2(50) NOT NULL,
    VALUE           VARCHAR2(400) NOT NULL,
    CONSTRAINT FK_RESOURCES_SUBSCRIPTION
        FOREIGN KEY (SUBSCRIPTION_ID)
        REFERENCES SUBSCRIPTION_MANAGER.SUBSCRIPTIONS (ID),
    CONSTRAINT CHK_RESOURCES_TYPE
        CHECK (RESOURCE_TYPE IN ('IP', 'VLAN', 'CPE', 'PORT', 'EQUIPMENT', 'NODE'))
);

-- Trigger for automatic RESOURCE ID generation
CREATE OR REPLACE TRIGGER SUBSCRIPTION_MANAGER.TRG_RESOURCE_ID
BEFORE INSERT ON SUBSCRIPTION_MANAGER.RESOURCES
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SUBSCRIPTION_MANAGER.SEQ_RESOURCE_ID.NEXTVAL
        INTO :NEW.ID
        FROM DUAL;
    END IF;
END;
/
