# Oracle Schema additions for the PRODUCT_OFFERING catalog (TM Forum alignment:
# `po` closes the gap between the documented external contract and the schema —
# see openspec/changes/product-offering-fk for the full rationale)

-- =========================
-- PRODUCT_OFFERING TABLE
-- =========================

CREATE TABLE SUBSCRIPTION_MANAGER.PRODUCT_OFFERING (
    ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL UNIQUE
);

INSERT INTO SUBSCRIPTION_MANAGER.PRODUCT_OFFERING (NAME) VALUES ('claroVideo');

ALTER TABLE SUBSCRIPTION_MANAGER.SUBSCRIPTIONS
    ADD PRODUCT_OFFERING_ID NUMBER;

ALTER TABLE SUBSCRIPTION_MANAGER.SUBSCRIPTIONS
    ADD CONSTRAINT FK_SUBSCRIPTIONS_PRODUCT_OFFERING
        FOREIGN KEY (PRODUCT_OFFERING_ID)
        REFERENCES SUBSCRIPTION_MANAGER.PRODUCT_OFFERING (ID);

-- Backfill: 2 rows on the live training DB already carry PO = 'claroVideo'
-- (discovered when applying this migration — the original assumption that
-- every row had PO empty did not hold). Resolve them to the new FK before
-- dropping PO, so no data is lost.
UPDATE SUBSCRIPTION_MANAGER.SUBSCRIPTIONS s
SET s.PRODUCT_OFFERING_ID = (
    SELECT po.ID FROM SUBSCRIPTION_MANAGER.PRODUCT_OFFERING po WHERE po.NAME = s.PO
)
WHERE s.PO IS NOT NULL;

-- A row with PO still non-null but PRODUCT_OFFERING_ID unresolved means PO held
-- a name with no matching PRODUCT_OFFERING row (an unseeded name) — the backfill
-- above couldn't resolve it, and dropping PO now would silently lose that value.
-- Fail loudly instead.
DECLARE
    unresolved_po_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO unresolved_po_count
    FROM SUBSCRIPTION_MANAGER.SUBSCRIPTIONS
    WHERE PO IS NOT NULL AND PRODUCT_OFFERING_ID IS NULL;

    IF unresolved_po_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20000,
            'Aborting: ' || unresolved_po_count || ' SUBSCRIPTIONS row(s) have a PO value with ' ||
            'no matching PRODUCT_OFFERING row. Seed that name into PRODUCT_OFFERING and re-run.');
    END IF;
END;
/

ALTER TABLE SUBSCRIPTION_MANAGER.SUBSCRIPTIONS DROP COLUMN PO;
