# Oracle Schema additions introducing SERVICE as a real entity
# (extracts PLATFORM/MSISDN/SIM_ICCID off SUBSCRIPTIONS into a new SERVICE table,
#  one row per subscription (1:1); RESOURCES gets a technically correct parent —
#  see docs/superpowers/specs/2026-08-26-service-entity-design.md)

-- =========================
-- SERVICE TABLE
-- =========================

CREATE SEQUENCE SUBSCRIPTION_MANAGER.SEQ_SERVICE_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE SUBSCRIPTION_MANAGER.SERVICE (
    ID              NUMBER PRIMARY KEY,
    SUBSCRIPTION_ID NUMBER NOT NULL UNIQUE,
    PLATFORM        VARCHAR2(100),
    MSISDN          VARCHAR2(400),
    SIM_ICCID       VARCHAR2(400),
    CONSTRAINT FK_SERVICE_SUBSCRIPTION
        FOREIGN KEY (SUBSCRIPTION_ID)
        REFERENCES SUBSCRIPTION_MANAGER.SUBSCRIPTIONS (ID)
);

-- Trigger for automatic SERVICE ID generation
CREATE OR REPLACE TRIGGER SUBSCRIPTION_MANAGER.TRG_SERVICE_ID
BEFORE INSERT ON SUBSCRIPTION_MANAGER.SERVICE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SUBSCRIPTION_MANAGER.SEQ_SERVICE_ID.NEXTVAL
        INTO :NEW.ID
        FROM DUAL;
    END IF;
END;
/

-- Backfill: one SERVICE row per existing SUBSCRIPTIONS row. Unlike the PO
-- backfill in 005, this cannot leave unresolved rows — every subscription
-- gets exactly one SERVICE row from its own data, no external catalog lookup.
INSERT INTO SUBSCRIPTION_MANAGER.SERVICE (SUBSCRIPTION_ID, PLATFORM, MSISDN, SIM_ICCID)
SELECT ID, PLATFORM, MSISDN, SIM_ICCID FROM SUBSCRIPTION_MANAGER.SUBSCRIPTIONS;

-- =========================
-- RESOURCES: FK swap from SUBSCRIPTION_ID to SERVICE_ID
-- =========================

ALTER TABLE SUBSCRIPTION_MANAGER.RESOURCES
    ADD SERVICE_ID NUMBER;

UPDATE SUBSCRIPTION_MANAGER.RESOURCES r
SET r.SERVICE_ID = (
    SELECT s.ID FROM SUBSCRIPTION_MANAGER.SERVICE s WHERE s.SUBSCRIPTION_ID = r.SUBSCRIPTION_ID
);

ALTER TABLE SUBSCRIPTION_MANAGER.RESOURCES
    MODIFY SERVICE_ID NOT NULL;

ALTER TABLE SUBSCRIPTION_MANAGER.RESOURCES
    ADD CONSTRAINT FK_RESOURCES_SERVICE
        FOREIGN KEY (SERVICE_ID)
        REFERENCES SUBSCRIPTION_MANAGER.SERVICE (ID);

ALTER TABLE SUBSCRIPTION_MANAGER.RESOURCES
    DROP CONSTRAINT FK_RESOURCES_SUBSCRIPTION;

ALTER TABLE SUBSCRIPTION_MANAGER.RESOURCES
    DROP COLUMN SUBSCRIPTION_ID;

-- =========================
-- SUBSCRIPTIONS: drop columns now owned by SERVICE
-- =========================

ALTER TABLE SUBSCRIPTION_MANAGER.SUBSCRIPTIONS DROP COLUMN PLATFORM;

ALTER TABLE SUBSCRIPTION_MANAGER.SUBSCRIPTIONS DROP COLUMN MSISDN;

ALTER TABLE SUBSCRIPTION_MANAGER.SUBSCRIPTIONS DROP COLUMN SIM_ICCID;
