INSERT INTO SUBSCRIBER_MANAGER.PLATFORM (NAME) VALUES ('FIXED_BSCS7');
INSERT INTO SUBSCRIBER_MANAGER.PLATFORM (NAME) VALUES ('FIXED_BSCS9');
INSERT INTO SUBSCRIBER_MANAGER.PLATFORM (NAME) VALUES ('MOBILE_INU');
INSERT INTO SUBSCRIBER_MANAGER.PLATFORM (NAME) VALUES ('MOBILE_BSCS9');
INSERT INTO SUBSCRIBER_MANAGER.PLATFORM (NAME) VALUES ('MOBILE_BSCS7');

INSERT INTO SUBSCRIBER_MANAGER.PAYMENT_MODE (NAME) VALUES ('OCC');
INSERT INTO SUBSCRIBER_MANAGER.PAYMENT_MODE (NAME) VALUES ('Saldo');
INSERT INTO SUBSCRIBER_MANAGER.PAYMENT_MODE (NAME) VALUES ('Credit Card');


